version: '3.7'

services:
  app-server:
    build:
      context: impl 
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    networks: 
      - backend
      - frontend

  app-client:
    build:
      context: search-customer-phone 
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
    ports:
      - "9090:80" 
    networks:
      - frontend  

networks:
  backend:
  frontend:   

  